# Dependencies
markdown:         kramdown
highlighter:      rouge

# Setup
title:            Report
tagline:          'GSOC 2017 project Report'
description:      'Google Summer of Code is almost over, so I wrote this post to give a overview over the targets I’ve met (and those I haven’t).'
url:              gsoc.amanskywalker.tk/
baseurl:          /

author:
  name:           'Aman'
  url:            www.amanskywalker.tk

# Custom vars
version:          1

github:
  repo:           https://github.com/Amanskywalker/gsoc-2017.git

gems :
  - jekyll-paginate
paginate: 2
paginate_path: "page:num"
