# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Setup
title:            Report
tagline:          'GSOC 2017 project Report'
description:      ''
url:              me.amanskywalker.tk/
baseurl:          /gsoc-2017/

author:
  name:           'Aman'
  url:            www.amanskywalker.tk

# Custom vars
version:

github:
  repo:           https://github.com/Amanskywalker/gsoc-2017.git

gems :
  - jekyll-paginate
paginate: 5
paginate_path: "page:num"
