# Dependencies
markdown:         kramdown
highlighter:      rouge

# Setup
title:            Report
tagline:          'GSOC 2017 project Report'
description:      'The Google Summer of Code is almost over, so I wrote this post to give a overview over the targets I’ve met (and those I haven’t).'
url:              me.amanskywalker.tk/
baseurl:          /gsoc-2017/

author:
  name:           'Aman'
  url:            www.amanskywalker.tk

# Custom vars
version:

github:
  repo:           https://github.com/Amanskywalker/gsoc-2017.git

gems :
  - jekyll-paginate
paginate: 2
paginate_path: "page:num"
